feat(ci): Add Tests to frontend ci

diff --git a/.github/workflows/frontend-ci.yml b/.github/workflows/frontend-ci.yml
--- a/.github/workflows/frontend-ci.yml
+++ b/.github/workflows/frontend-ci.yml
@@ -25,3 +25,14 @@ jobs:
 
       - name: Run lint and format check
         run: npm run lint
+
+      - name: Run tests
+        run: npm test -- --ci --reporters=jest-junit
+
+      - name: Upload test reports
+        if: success() || failure() # Always upload even if tests fail
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-reports
+          path: frontend/test-results
+          retention-days: 7
